import { NextRequest, NextResponse } from "next/server"
import { getBookingJob, savePaystackUrl } from "@/lib/booking-job"
import { releaseHold } from "@/lib/booking-holds"
import { buildGuestPendingEmail, initiatePaystackPayment } from "@/lib/payment-utils"
import { transitionBookingStatus, type BookingStatus } from "@/lib/booking-status"
import { Resend } from "resend"

export const dynamic = "force-dynamic"

/**
 * Polled by /booking/processing while the pre-payment NightsBridge booking
 * runs in the background. Drives the booking_status state machine (see
 * lib/booking-status.ts) forward as far as it can go on each poll:
 *
 *   NIGHTSBRIDGE_VERIFIED -> CONFIRMATION_EMAIL_SENT -> AWAITING_PAYMENT
 *
 * The transition INTO CONFIRMATION_EMAIL_SENT is the atomic claim on "send
 * the guest email + generate the Paystack session" — only the poll that wins
 * that compare-and-swap does it, so it happens exactly once no matter how
 * many times this endpoint is polled or if the process restarts mid-way
 * (the next poll just finds booking_status already past that point and skips
 * straight to reading back the stored payment URL).
 */
export async function GET(request: NextRequest) {
  const reference = new URL(request.url).searchParams.get("reference") ?? ""
  if (!reference) {
    return NextResponse.json({ status: "unknown", error: "Missing reference" }, { status: 400 })
  }

  const { job, dbError } = await getBookingJob(reference)

  if (dbError) {
    // A genuine DB read failure (bad credentials, RLS denial, connection
    // issue) — NOT the same as "the job just hasn't resolved yet". Reported
    // as "processing" on the wire (a transient blip shouldn't fail the guest's
    // booking), but logged loudly and distinctly so a PERSISTENT failure is
    // immediately visible in server logs instead of looking identical to a
    // slow-but-healthy booking.
    console.error(`[booking/status] DB READ ERROR reference=${reference}: ${dbError} — reporting 'processing' to avoid failing on a transient blip`)
    return NextResponse.json({ status: "processing" })
  }

  if (!job) {
    return NextResponse.json({ status: "processing" })
  }

  // The sync-worker service (services/sync-worker/server.py) is deployed
  // independently of this app. Until it's redeployed with the matching
  // rename, it still writes the old "pending"/"booked" values — normalize
  // those here so a real success/in-progress isn't misread as unresolved
  // regardless of which side has deployed the rename first.
  const rawStatus = job.status as string
  const status = rawStatus === "booked" ? "completed" : rawStatus === "pending" ? "processing" : job.status

  if (status === "completed" || status === "failed") {
    await releaseHold(reference)
  }

  let bookingStatus = job.booking_status as BookingStatus

  // The worker writes status=failed but doesn't know about booking_status
  // (Python side transitions its own successful stages — see server.py — but
  // a hard failure there is simplest to catch here where we already read the
  // row). FAILED is a legal target from every non-terminal stage, so this
  // transition succeeds regardless of exactly where it died.
  if (status === "failed" && bookingStatus !== "FAILED") {
    await transitionBookingStatus(reference, "FAILED", { reason: job.error ?? "booking failed" })
    bookingStatus = "FAILED"
  }

  // Read back a Paystack URL already generated by an earlier ("winning") poll,
  // so every poll after the first can still hand the guest the SAME link.
  let paymentUrl = (job.context as { paystackUrl?: string } | null)?.paystackUrl || ""

  if (bookingStatus === "NIGHTSBRIDGE_VERIFIED") {
    const claimed = await transitionBookingStatus(reference, "CONFIRMATION_EMAIL_SENT", {
      from: ["NIGHTSBRIDGE_VERIFIED"],
    })
    if (claimed.ok) {
      // Generate the ONE Paystack session for this booking here, server-side,
      // so it can be embedded in the email AND returned for the redirect —
      // never two separate sessions for the same booking.
      const amountRands = job.amount ? Number(job.amount) : 0
      if (job.guest_email && amountRands > 0) {
        const payment = await initiatePaystackPayment({
          email: job.guest_email,
          amountRands,
          bookingRef: job.booking_id ?? reference,
          internalReference: reference,
          guestName: job.guest_name ?? "",
          checkin: job.checkin ?? "",
          checkout: job.checkout ?? "",
          roomTypeName: job.room_type_name ?? "",
          roomName: job.room_name ?? "",
        })
        if (payment.ok) {
          paymentUrl = payment.authorization_url
          await savePaystackUrl(reference, paymentUrl)
        } else {
          console.error(`[booking/status] Paystack pre-generation failed reference=${reference}: ${payment.error}`)
        }
      }

      const resendKey = process.env.RESEND_API_KEY
      if (resendKey && resendKey !== "re_REPLACE_ME" && job.guest_email) {
        try {
          const resend = new Resend(resendKey)
          const from = process.env.RESEND_FROM_EMAIL ?? "Boga Legaba <onboarding@resend.dev>"
          await resend.emails.send({
            from,
            to: job.guest_email,
            subject: "Your room is reserved – complete payment – Boga Legaba",
            html: buildGuestPendingEmail({
              guestName: job.guest_name ?? "",
              bookingRef: job.booking_id ?? "",
              checkin: job.checkin ?? "",
              checkout: job.checkout ?? "",
              roomTypeName: job.room_type_name ?? "",
              roomName: job.room_name ?? "",
              estimatedTotal: job.amount ? `R ${Number(job.amount).toLocaleString("en-ZA", { minimumFractionDigits: 2 })}` : "",
              paymentUrl,
            }),
          })
        } catch (err) {
          console.error("[booking/status] Guest pending email error:", err)
        }
      }

      await transitionBookingStatus(reference, "AWAITING_PAYMENT", { from: ["CONFIRMATION_EMAIL_SENT"] })
      bookingStatus = "AWAITING_PAYMENT"
    }
  }

  return NextResponse.json({
    status,
    bookingStatus,
    bookingRef: job.booking_id ?? "",
    error: job.error ?? "",
    guestName: job.guest_name ?? "",
    guestEmail: job.guest_email ?? "",
    checkin: job.checkin ?? "",
    checkout: job.checkout ?? "",
    roomTypeName: job.room_type_name ?? "",
    roomName: job.room_name ?? "",
    amount: job.amount ?? "",
    paymentUrl,
  })
}
